#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Execute lint-staged
npx lint-staged --verbose

# Test + Lint
yarn run lint
yarn run test --watchAll=false --passWithNoTests

# Validate branch name
npx branch-name-lint .branch-name-list.json
